// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'button-cancel'
  | 'button-overwrite'
  | 'button-overwrite-all'
  | 'error-batch-error-title'
  | 'error-no-regular-item'
  | 'menu-authors'
  | 'menu-both'
  | 'menu-container'
  | 'menu-map-path'
  | 'menu-root'
  | 'pref-auto-process'
  | 'pref-auto-process-desc'
  | 'pref-help'
  | 'pref-title'
  | 'prompt-overwrite-message'
  | 'prompt-overwrite-title';
